### ISSUE TITLE
Custom AppRun file not applied

### ISSUE THREAD

**Issue by RealLucioCarreras** [linuxdeploy/linuxdeploy#100]
Hello,
first of all, thank you a lot for this project. You made a developer's life a lot easier.
I face a little issue. Currently I have a workaround for it but I am not quite sure if this is a bug or just wrong usage on my side.

I have a custom AppRun file in my project and I want to apply it to my project instead of the autogenerated one. But it seems not to be copied to the AppDir directory

I call your tool with
``linuxdeploy-x86_64.AppImage --appdir=AppDir --custom-apprun=../AppImage/AppRun  --desktop-file=./AppDir/usr/share/applications/myapp.desktop --plugin=qt ``

Everything runs through, exiting with 0, perfect.
The last few lines of the program's output are
```
-- Deploying files into AppDir root directory -- 
Deploying custom AppRun:  /home/luke/git/myapp/AppImage/AppRun 
Deploying file /home/luke/git/myapp/AppImage/AppRun to AppDir/AppRun 
Copying file /home/luke/git/myapp/AppImage/AppRun to AppDir/AppRun 
Deploying files to AppDir root using desktop file: AppDir/usr/share/applications/myapp.desktop 
Deploying desktop file to AppDir root: AppDir/usr/share/applications/myapp.desktop 
Creating symlink for file AppDir/usr/share/applications/myapp.desktop in/as AppDir 
Deploying icon to AppDir root: AppDir/usr/share/icons/hicolor/72x72/apps/myapp.png 
Creating symlink for file AppDir/usr/share/icons/hicolor/72x72/apps/myapp.png in/as AppDir 
Deploying custom AppRun: /home/luke/git/myapp/AppImage/AppRunCopying file /home/luke/git/myapp/AppImage/AppRun to AppDir/AppRun
```
So everything seems that my custom AppRun is copied to the AppDir. But in the AppDir directory the AppRun file is just the autogenerated one, not mine

Thank you in advance

**Comment by TheAssassin** [comment]
I use the custom AppRun option every day, and I've never seen any behavior like that.

You don't have to specify `--desktop-file`, that option is for desktop files outside the AppDir and will cause linuxdeploy to copy it to the AppDir in exactly that location. Perhaps that confuses linuxdeploy? Please try omitting the flag and I'll have a look.

> `Copying file /home/luke/git/myapp/AppImage/AppRun to AppDir/AppRun`

That path is correct?

Please note that as you're using the Qt plugin, your file should end up in `AppDir/AppRun.wrapped` after linuxdeploy finished. If "the auto-deployed one" means "some autogenerated file", it's regular behavior. The Qt plugin installs a hook script that needs to be run before executing the application, that's why that script is needed.

**Comment by RealLucioCarreras** [comment]
My path structure is roughly:
```
myapp
  - AppImage
    - AppRun 
  - src
  - build
    - AppDir
```
I am calling the script from ``myapp/build``

> your file should end up in AppDir/AppRun.wrapped after linuxdeploy finished
Ah, ok. I see. Everything I was looking for is in the AppRun.wrapped. I didn't look into this file because I thought that only the ``XDG_CURRENT_DESKTOP`` stuff is evaluated there.

I just tried it out and everything worked great. Thank you!
