### ISSUE TITLE
Could not find patchelf caused by non-unique /tmp/ directory

### ISSUE THREAD

**Issue by mnil** [linuxdeploy/linuxdeploy#174]
We use linuxdeploy building multiple targets using the bazel build system by Google. In our setup we have had problems with flaky failures with the symptom:
```
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Could not find patchelf
```
after some debugging we drew the conclusion that this is due using the `--appimage-extract-and-run` which extracts to `  /tmp/appimage_extracted_<hash>`. Since we have multiple targets and bazel is using multiple threads I think the extraction is removing some files used by the other linuxdeploy process. We can't run the AppImage directly either due to the build system running in a docker container.

We solved this by using the `linuxdeploy-x86_64.AppImage --appimage-extract && ./squashfs-root/AppRun <args> && rm -rf ./squashfs-root`. Then every build target gets a unique AppRun. One could maybe mitigate this by using a more unique hash in the /tmp/-dir? Maybe this is a very small use case, but I submit this issues in case anyone else is having the same problem in the future. If you not feel like this is worth a fix just close the issue.

**Comment by TheAssassin** [comment]
Interesting catch, but this is probably the wrong place for the discussion. You might want to start it over at AppImageKit, which is where the runtime is being maintained.

In any case, you can also use `export NO_CLEANUP=1`, which prevents the runtime from, well, cleaning up the files after the process terminated.

The reason the hash is there is to basically prevent the runtime from having to re-extract everything on every execution. This is also why there is `NO_CLEANUP`. Parallel execution was, however, not taken into account, this system is designed for consecutive calls. With `NO_CLEANUP`, parallel execution should work as well, though. I guess most people don't care nowadays since they create Docker containers for every build anyway.

Your solution extracting to different directories is surely cleaner. You could suggest this feature for the upstream runtime.

**Comment by mnil** [comment]
Thanks for fast response! I will add this to the AppImageKit and they can fix it if they want.
