### ISSUE TITLE
Problems trying to deploy WebEngine on AppVeyor using Qt6 and cmake

### ISSUE THREAD

**Issue by Light-Wizzard** [linuxdeploy/linuxdeploy#186]
I have no idea how to troubleshoot this error message:

```
ERROR: qmlimportscanner: could not find a Qt installation of ''
```

This is a fork of the Viper Browser https://github.com/Light-Wizzard/WeBookBrowser,
the log file is here https://ci.appveyor.com/project/Light-Wizzard/webookbrowser.

AppVeyor does not have WebEngine or Multimedia, I emailed them about adding support for Qt6,
till then I have to upload all the missing files from a diff I did, details at the first link.

How do I figure out what the blank '' is?

Thanks, Flesh

**Comment by TheAssassin** [comment]
That's not a linuxdeploy issue. You might have wanted to open an issue over at linuxdeploy-plugin-qt. However, it's not an issue there as well. This issue is related to a missing package. Therefore, closing here.

On Ubuntu/Debian, there is a package called `qtchooser` which causes this error message. Try to install `qtdeclarative5-dev-tools` (found with `apt-file search qmlimportscanner`).

**Comment by Light-Wizzard** [comment]
That got me past that error, thanks.

Can you do everyone a favor and start a Troubleshooting page in the Wiki, and put this in there, I would have never figured this one out. 

I would just do FYI-type bullet statements of common errors and how to troubleshoot them, you can add them as they come up so others can benefit from them, and it will save you a lot of common questions like this to answer.

Thanks, Flesh
