### ISSUE TITLE
Consider a Gtk+ plugin

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy#2]
(Low priority, mainly a placeholder for the link below I just stumbled across)

Consider a Gtk+ plugin that would bundle the subset of Gtk+ that is needed.
Maybe some code (or inspiration) from https://github.com/jralls/gtk-mac-bundler could be adopted.

**Comment by TheAssassin** [comment]
I'd love to see someone maintain such a plugin externally. Do you know anybody who might be interested in that?

**Comment by probonopd** [comment]
Maybe @aferrero2707?

**Comment by TheAssassin** [comment]
Such a plugin might use https://github.com/TheAssassin/linuxdeploy-plugin-qt for inspiration. This plugin re-uses facilities maintained by the linuxdeploy authors to deploy files into the AppDir.

**Comment by TheAssassin** [comment]
@probonopd is there any code that showcases what needs to be done to bundle Gtk+?

**Comment by probonopd** [comment]
Not that I am aware of

**Comment by aferrero2707** [comment]
@TheAssassin @probonopd I think that my [GIMP AppImage script](https://github.com/aferrero2707/gimp-appimage/blob/master/mkappimage) can be taken as a good example of bundled GTK+ app, which is also fully relocatable.

Is there a specific reason for using C/C++ for [the Qt plug-in[(https://github.com/TheAssassin/linuxdeploy-plugin-qt), instead of simple bash?

**Comment by aferrero2707** [comment]
@TheAssassin I have recently done some more work that attempts to generalise the bundling of GTK applications, partly also inspired by your [linuxdeploy-plugin-checkrt](https://github.com/TheAssassin/linuxdeploy-plugin-checkrt) code.

The current scripts can be found here: https://github.com/aferrero2707/appimage-helper-scripts, and an example of bundling script here: https://github.com/aferrero2707/pf-build-appimage/blob/master/package-appimage.sh

In particular, I took your environment hacking code, but changed a couple of details:
* the initial environment is saved with an explicit redirection of `env | tr '\n' '\0'` into a temporary file, which is then read back by `read_env_from_process()` (see [here](https://github.com/aferrero2707/appimage-helper-scripts/blob/master/appimage-exec-wrapper2/env.c#L90))
* the `APPDIR` environment variable is replaced by a colon-separated list of paths in `APPDIRS`

The custom [functions.sh](https://github.com/aferrero2707/appimage-helper-scripts/blob/master/functions.sh) and [bundle-gtk2.sh](https://github.com/aferrero2707/appimage-helper-scripts/blob/master/bundle-gtk2.sh) scripts provide a set of standard functions that help automating the bundling process, while [apprun-helper.sh](https://github.com/aferrero2707/appimage-helper-scripts/blob/master/apprun-helper.sh) provides some helper functions for the main `AppRun` script, as shown for example [here](https://github.com/aferrero2707/pf-build-appimage/blob/master/AppRun.sh).

I can explain all the details if you are interested.

**Comment by TheAssassin** [comment]
It would be great if you could convert your code into a linuxdeploy plugin to make deploying GTK software as easy as never before. It would be great if you as a sort-of-GTK-expert could maintain that. Also, we'd have a consistent user experience.
If you implemented it in C++, you could even save yourself quite some code as linuxdeploy provides a lot of it already in its core library.

Not sure what you mean with `$APPDIRS`.

**Comment by probonopd** [comment]
Would help the cause if you could closely work together on this,  @aferrero2707 and @TheAssassin. From what I observed, the Gtk+ developer community does not really embrace C++ but uses C with glib. Hence it might be worthwhile to implement the Gtk+ plugin using that stack, so that it comes naturally to Gtk+ developers.

**Comment by aferrero2707** [comment]
I'm maybe too pessimistic, but I don't expect much help from the GTK devs on this, so I would go for whatever language is more appropriate.

No problem to collaborate with @TheAssassin.

One technical question: does the code support hooks for custom scripts to be run during the bundling process, or should one always implement a plugin?

**Comment by aferrero2707** [comment]
@TheAssassin 
Let me give you a practical example. In the GIMP case, on top of the "standard" GTK libraries/configuration files I need to bundle some folders that are specific to GIMP.
Moreover, since GIMP is compiled from sources they are in a different prefix.

Here is an example: https://github.com/aferrero2707/gimp-appimage/blob/master/package-appimage.sh#L285

Such cases cannot be handled by a "generic" GTK linuxdeploy plug-in, hence the need of some "hooks" that allow to run some application-specific commands/actions on top of the generic ones.

I hope it is more clear now.

Anyway, I am planning to start coding some GTK plugin during next week, following the Qt example.

**Comment by aferrero2707** [comment]
> The best I could come up is to add a directory in the AppDir

This si also what I was thinking about: a folder populated by hook scripts, that can be prioritised with a numerical prefix.

By the way, as I was trying to explain, a similar problem exists when *populating* the AppDir, because there can be some application-specific things that need to be bundled and that cannot be handled by a generic infrastructure. For example, GIMP has its own configuration files that need to be copied into the AppDir.

My idea would be to solve this problem in the same way, i.e. a folder where to put hook scripts prior to running `linuxdeploy`.

I will try to come up with a working example during the next days.

**Comment by TheAssassin** [comment]
> that can be prioritised with a numerical prefix.

I think we should standardize that hooks must not expect to be run in a specific order. If we combine that with a rule that scripts must allow for multiple execution, scripts could check for other scripts, and run them before they make their own changes. Then, you can have a guaranteed, script-specified order of execution.

**Comment by X0rg** [comment]
I think this issue can be closed: https://github.com/linuxdeploy/linuxdeploy-plugin-gtk

**Comment by TheAssassin** [comment]
Indeed. Thanks.
