### ISSUE TITLE
Bundling libc and libstdc++

### ISSUE THREAD

**Issue by aurelienpierre** [linuxdeploy/linuxdeploy#237]
I'm building [Ansel](https://github.com/aurelienpierreeng/ansel/) using [this script](https://github.com/aurelienpierreeng/ansel/blob/master/.ci/ci-script-appimage.sh), on Fedora 37 (GCC 12, GLibC 2.36). The produced AppImage can be [downloaded here](https://github.com/aurelienpierreeng/ansel/releases/tag/v0.0.0). It works for me®.

However, an user testing it on Ubuntu 20.04 (GlibC 2.31) got [these errors](https://pastebin.com/vLCjKnxL). 

I understand that basic Linux libs are [excluded from bundling](https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist). Since Fedora typically ships bleeding-edge libs and Ubuntu LTS are a bit more conservative, I guess the issue is my package is built against libs that are too new and need to be bundled as well.

Is there a way to bypass the excluded libs to make the package really portable, aka to force bundling GlibC and other essential libs ?

**Comment by TheAssassin** [comment]
There's https://github.com/linuxdeploy/linuxdeploy-plugin-checkrt which allows bundling libstdc++ but not libc.

Bundling libc is always a very bad hack and is subject to so many pitfalls. linuxdeploy doesn't support that. It's not worth it the time and effort to maintain. 

Consider building all your dependencies on some older system. Even good ol' CentOS 7 can utilize recent gcc/g++ using `devtoolset` (that kind of setup doesn't even require checkrt). Otherwise, what works, too, if you don't need a recent libc is to build on some Ubuntu LTS like 18.04 or even 20.04 with a distribution provided, more recent gcc (20.04 provides packages for `gcc-10` for instance, and there also is `ubuntu-toolchain-r` which can be used to use a C++17-capable C++ compiler in combination with the standard C compiler on the oldest still-supported Ubuntu LTS release 18.04, as shown in [AppImageUpdate](https://github.com/AppImageCommunity/AppImageUpdate/blob/main/ci/Dockerfile.x86_64#L30)).

**Comment by aurelienpierre** [comment]
Thanks for the answer. I tried Ubuntu 20.04 but I have the issue #238 then.
