### ISSUE TITLE
Is there a way to re-squash an extracted/modified squashfs-root?

### ISSUE THREAD

**Issue by spiderkeys** [linuxdeploy/linuxdeploy#277]
There may be a better way to accomplish what we are doing, but we have the need to make modifications to the AppImage after it has been generated by the initial invocation of linuxdeploy, mainly to de-duplicate a ton of libraries that we bundle into the AppImage (provided by the conan c++ package manager).

Our workflow:
1. Use conan to install deps into `Appimagedir/opt/lib/thirdparty`
2. Run linuxdeploy (it also finds most shared libs that were linked against in the executable, except run-time loaded stuff, and puts them in `Appimagedir/usr/lib/`)
3. Extract the appimage
4. Delete the duplicate libraries from `Appimagedir/usr/lib`, such that `Appimagedir/opt/lib/thirdparty` is where most of the libs come from (barring system dependencies like X11 libs)
5. Re-package the squashfs-root into an AppImage with the modified contents

**Comment by TheAssassin** [comment]
If the copies are identical byte wise, squashfs will deduplicate them anyway. Other than that, you could set up your own linuxdeploy plugin (plugins can be anything, including shell scripts, see, e.g., https://github.com/linuxdeploy/misc-plugins/) to do the cleanup right before the output plugin (ld-p-appimage) runs. That is a bit of a workaround but it'll yield the desired result.

Why don't you install your third-party libs directly into `usr/lib`, though? Also, why not just delete `/opt` entirely after linuxdeploy ran (for the first time without `--output`)?

**Comment by mralusw** [comment]
Is it possible to *not* pack the appimage at all, and just let the `appDirPath` with all the work LinuxDeploy did *be* the output? Something like `--output appdir`? For one thing, linuxdeploy currently uses an "old" appimagetool (or its equivalent), which does not support zstd compression. I'd rather prefer packing the output AppDir manually using a release from `https://github.com/AppImage/appimagetool/`, rather than whatever linuxdeploy incorporates internally.

**Comment by spiderkeys** [comment]
@TheAssassin about installing the libraries into `usr/lib`, you're right, I can do this but I lose a little clarity when it comes to debugging later on. Originally I was keeping them separate so that it is very clear in the directory structure (and when debugging with LD_DEBUG) which libraries came from conan, which came from `linuxdeploy`, and which are getting loaded from the host system outside of the AppImage. In general, this helps me keep track dependencies I still need to capture with conan (as I always try to minimize the reliance on system dependencies).

`conan` is able to model dynamically loaded libraries as well, as they are explicitly specified in the recipe for each dependency in the dependency tree, while `linuxdeploy` is only detecting the libraries that the application directly linked (unless a specific plugin provides additional support, like for qt or gstreamer). What conan doesn't capture/install are the system libraries that end up getting used (in the cases where a conan recipe doesn't or can't realistically be created for a dependency, like the X11 libraries). `linuxdeploy` happily identifies and deploys those libraries for me, so I use conan to deploy the complete dependency tree for all conan-modeled deps, and let `linuxdeploy` backfill the system deps.

What I ended up doing effectively achieves what @mralusw is suggesting here. My current steps are:
1. Install the conan deps to /opt/
2. Let `linuxdeploy` install everything it finds to /usr/ and build the appimage
3. Run --appimage-extract on the resulting .AppImage
4. Delete duplicate libraries in /usr/
5. Re-package the modified squashfs dir using a separate `appimagetool`

It's good to know about the `misc-plugins` repo and that workflow though, so thanks for sharing that.

**Comment by mralusw** [comment]
@spiderkeys I found a much simpler way to skip appimage packing. Simply create a "dummy" output plugin `linuxdeploy-plugin-nop.sh` next to `linuxdeploy`, and run `linuxdeploy --appdir app.AppDir... --output nop`. The "plugin" is absolutely trivial, but since I need to do this from GH actions in other projects, I've packaged it at [`linuxdeploy-plugin-nop`](https://github.com/kstr0k/linuxdeploy-plugin-nop/).

`linuxdeploy` does all the hard work of modifying `app.AppDir` and&hellip; exits. Then you can run the pre-release [appimagetool](https://github.com/AppImage/appimagetool/) on the modified `app.AppDir` &mdash; complete with zstd compression (including non-default compression level and squashfs block-size via repeated `--mksquashfs-opt ...` args).

If my findings are correct, you could also simply ignore the AppImage and use the modified AppDir instead of re-extracting; which wastes (a possibly large amount of) time, hence this.

@TheAssassin I have to say I appreciate the flexibility of linuxdeploy, it really does alleviate the problem of imperfect defaults / missing options.

**Comment by mralusw** [comment]
It turns out that simply running `linuxdeploy` without a `--output` flag modifies the AppDir without packing it into an AppImage. I've tested this previously (as it was the most obvious thing), but apparently incorrectly.

No need to generate an AppImage and extract it.

**Comment by spiderkeys** [comment]
Good to know, thanks for sharing @mralusw. I'll go ahead and close this now, since that cleanly solves the problem.

**Comment by TheAssassin** [comment]
@mralusw is right. linuxdeploy calls itself "AppDir maintenance tool" for a reason. Its primary work item is an AppDir. It can produce more than just AppImages by the way, `.deb`s and `.rpm`s are another format it produces. It would further be really easy to, e.g., `zip` the files.
