### ISSUE TITLE
could not find suitable executable for Exec entry: env

### ISSUE THREAD

**Issue by Ketrel** [linuxdeploy/linuxdeploy#285]
It looks like the exec line in question is

`Exec=env QT_QPA_PLATFORM=xcb dolphin-emu`

**Comment by TheAssassin** [comment]
There is almost no information in this issue. No link to a binary or repository, no logging, nothing. Closing therefore. Feel free to open a new issue with more information.

**Comment by BLumia** [comment]
I'm having the exact same issue today, here are the detailed information if you are interested:

- build log: https://github.com/BLumia/pineapple-tracker-player/actions/runs/10433366949/job/28895015563#step:6:1183
- related source: https://github.com/BLumia/pineapple-tracker-player/blob/da13e12e8efcd90f0cb764ba685fa6c8d87fb19d/dist/net.blumia.pineapple-tracker-player.desktop (use `da13e12e8efcd90f0cb764ba685fa6c8d87fb19d` revision if you want the full source code of that specific CI run)

I don't plan to open a new issue for this because I'm going to change my `.desktop` file's `Exec` line anyway thus it's no longer going to start with `env`, but hope this information helps.
