### ISSUE TITLE
Dependencies of symbolic links ignored

### ISSUE THREAD

**Issue by darealshinji** [linuxdeploy/linuxdeploy#70]
Dependencies are not tracked when my AppDir has a symbolic link in `AppDir/usr/bin` that points to a binary that isn't in `AppDir/usr/bin` or `AppDir/usr/lib`.

Dependencies are **not** found:
```
AppDir/usr/bin/foo -> symbolic link to ../program/foo
AppDir/usr/program/foo
```

Dependencies are found:
```
AppDir/usr/bin/foo -> symbolic link to ../lib/foo/foo
AppDir/usr/lib/foo/foo
```

**Comment by TheAssassin** [comment]
I can't see any reason in the codebase that would prevent the deployment of symlinked files. The respective method just returns a list of all files in `usr/bin`. Perhaps we need to resolve any symlinks in there before checking whether they are ELF files. Although, on the other hand, the ELF file helper just uses an `std::ifstream` to read the files and check for magic bytes. See also https://github.com/linuxdeploy/linuxdeploy/blob/master/src/core/elf.cpp#L116.

**Comment by TheAssassin** [comment]
Please excuse my own ignorance. 

https://github.com/linuxdeploy/linuxdeploy/blob/956a253428bbae8593e07678709de4264ce77ae6/src/core/appdir.cpp#L844-L850

Symlinks are explicitly skipped. I wonder why, though. There's unfortunately no explanatory comment.

If I think about it, I'm pretty sure the reason is that plugins like the `conda` one create symlinks in `usr/bin` that point to executables whose dependencies must not be deployed, as they're handled in a different directory anyway.

The quick fix (and from my point of view, the recommended way) is to copy the files instead of symlinking them. Then they're properly recognized. And squashfs supports deduplication anyway, so there won't be redundant data in the AppImage.

**Comment by darealshinji** [comment]
> And squashfs supports deduplication anyway, so there won't be redundant data in the AppImage.

Good to know.

**Comment by TheAssassin** [comment]
Closing as wontfix. Please see the workaround in https://github.com/linuxdeploy/linuxdeploy/issues/70#issuecomment-465583991.
