### ISSUE TITLE
Linuxdeploy fails to run on Debian 8

### ISSUE THREAD

**Issue by Clodo76** [linuxdeploy/linuxdeploy#94]
Linuxdeploy fails to run on Debian 8.
`"version 'GLIBCXX_3.4.21' not found`

I need to compile my app on x64, x86 and armhf (raspberry).
For armhf, no linuxdeploy download exists.
My build environment (for x64 and x86) it's a Debian 8
(EOL, but if i use a recent version, i have the GLIBCXX problem myself on CentOS).

I resolved on Debian8 x64 by using the centos6-x86_64 version, but doesn't exists a centos6-i686.

I will try to compile linuxdeploy by myself, consider this issue as a feedback and close direct, maybe about compiling official release with more compatible glibc.

**Comment by TheAssassin** [comment]
linuxdeploy is built on Ubuntu 16.04. Debian 8 is oldstable and was released 2015, so the regular AppImages can't run there.

We have plans to move CI to older distros again, but there's no rush yet. As for a i386 centos6 version, I haven't had time to set up 32-bit builds yet.

Compiling yourself will work for sure, since linuxdeploy is pure C++11 (and its dependencies are <= C++11). We used to build on trusty just fine. Unfortunately trusty is EOL, and I don't want to provide AppImages built on such an old, unmaintained OS.
